name: 'Create github release'
description: ''
inputs:
  version:
    description: 'target version'
    required: true
  attachments:
    description: '[CSV] attachments to uplaod to the release (accept globs)'
    required: false
    default: ''
  github-token:
    required: false
    description: 'github token to be used'
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - run: |
        [ ! -f "~/go/bin/create-github-release" ] && mkdir -p ~/go/bin && curl -L https://github.com/upfluence/actions/releases/latest/download/create-github-release > ~/go/bin/create-github-release
      shell: bash
    - run: chmod +x ~/go/bin/create-github-release
      shell: bash
    - run: ~/go/bin/create-github-release --release-version ${{ inputs.version }} --attachments '${{ inputs.attachments }}'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
