name: 'Create github release'
description: ''
inputs:
  version:
    description: 'target version'
    required: true
  attachments:
    description: '[CSV] attachments to uplaod to the release (accept globs)'
    required: false
    default: ''
  latest:
    description: 'mark the release as latest'
    required: false
    default: 'true'
  github-token:
    required: false
    description: 'github token to be used'
    default: ${{ github.token }}
  cli-version:
    required: false
    description: 'version of the cli to use'
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - run: bash "$GITHUB_ACTION_PATH/../scripts/download-cli" create-github-release ~/go/bin/create-github-release '${{ inputs.cli-version }}' '${{ github.action_ref }}'
      shell: bash
    - run: ~/go/bin/create-github-release --release-version ${{ inputs.version }} --attachments '${{ inputs.attachments }}'${{ inputs.latest != 'true' && ' --prerelease' || '' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
