name: any-js-lint_and_test

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20"
      timeout-minutes:
        required: false
        type: number
        default: 10
      scenarios:
        type: string
        default: ""
      test-variants:
        type: string
        default: '[{"name":"default","command":"pnpm test:ember"}]'
      compatibility-blocking:
        type: boolean
        default: false
      ember-try-working-directory:
        type: string
        default: "."

env:
  NODE_VERSION: ${{ inputs.node-version }}
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  GIT_TERMINAL_PROMPT: "0"
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    if: |
      !contains('refs/heads/master refs/heads/main', github.ref) ||
      contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Configure GitHub Git authentication
        run: |
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          git config --global --add url."https://github.com/".insteadOf "git@github.com:"
          git config --global --add url."https://github.com/".insteadOf "git+ssh://git@github.com/"
          git config --global credential.https://github.com.helper '!f() { if [ "$1" = get ]; then printf "%s\n" "username=x-access-token" "password=$GITHUB_TOKEN" ""; fi; }; f'
      - uses: pnpm/action-setup@v4
        with:
          version: '${{ vars.PNPM_VERSION }}'
      - uses: actions/setup-node@v6
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Lint
        run: pnpm lint:js
      - name: Lint HBS
        run: pnpm prettier -c **/*.hbs
  test:
    uses: ./.github/workflows/any-js-ember-test.yml
    secrets: inherit
    with:
      node-version: ${{ inputs.node-version }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
      scenarios: ${{ inputs.scenarios }}
      test-variants: ${{ inputs.test-variants }}
      compatibility-blocking: ${{ inputs.compatibility-blocking }}
      ember-try-working-directory: ${{ inputs.ember-try-working-directory }}
