name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: go test -v ./...
  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: test
    if: contains('refs/heads/master', github.ref)
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Bump version
        id: bump-version
        uses: ./bump-version
      - name: Compile binaries
        uses: ./compile-go
        with:
          executable-paths: ./bump-version,./compile-go,./create-github-release
          linker-mode: cli
          dist-dir: dist/
          version: ${{ steps.bump-version.outputs.version }}
      - name: Create release
        uses: ./create-github-release
        with:
          attachments: dist/*
          version: ${{ steps.bump-version.outputs.version }}
