name: lib-ruby-test

on:
  workflow_call:
    inputs:
      ruby-version-matrix:
        required: false
        type: string
        default: "['3.4.1', '3.3.3']"
      timeout-minutes:
        required: false
        type: number
        default: 10

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    strategy:
      matrix:
        ruby-version: ${{ fromJSON(inputs.ruby-version-matrix) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Run the Test Suite
      run: |
        bundle exec rspec --color --require spec_helper --format progress spec
