name: linter
on: [pull_request]

jobs:
  lint:
    name: runner / golangci-lint
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: golanci-lint
        uses: upfluence/action-golangci-lint@master
